language: php
php:
    - '7.3'
cache:
    directories:
        - "$HOME/.composer/cache"

install:
  - npm install retire --save-dev
  - npm install jshint -save-dev
  - npm install twly --save-dev

script:
  - jshint ./
  - retire 
  - twly