language: php
php:
    - '7.3'
cache:
    directories:
        - "$HOME/.composer/cache"

install:
  - npm install -g retire
  - npm install -g jshint
  - npm install -g twly

script:
  - jshint ./src
  - retire 
  - twly

# pas eu le temps d'installer ruby et co pour pouvoir run la command "travis encrypt $(heroku auth:token) --add deploy.api_key" pour obtenir la clé
#deploy:
#    provider: heroku
#    api_key:
#      secure: clé obtenu avec travis encrypt $(heroku auth:token) --add deploy.api_key
#    app: ipssi-evaluation-nm