language: php
php:
    - '7.3'
cache:
    directories:
        - "$HOME/.composer/cache"

install:
  - npm install -g retire
  - npm install -g jshint
  - npm install -g twly

script:
  - jshint ./
  - retire 
  - twly